### ISSUE TITLE
Chrome Custom Tabs

### ISSUE THREAD

**Issue by kartikarora** [LUGM/LUGMNotifier#16]
Currently, the items in nav/side bar open in a new browser window. Instead, they should open in the app itself using [Chrome Custom Tabs](https://developer.chrome.com/multidevice/android/customtabs)

**Comment by kartikarora** [comment]
@sakethkaparthi would you like to work on this, since you have done it earlier?

**Comment by sakethkaparthi** [comment]
@chipset95 okay. i will do it.
